### ISSUE TITLE
Can't grant device owner permission

### ISSUE THREAD

**Issue by Xisrr1** [BinTianqi/OwnDroid#19]
Even after removing all accounts I will get an error that there are still accounts on this device. Profile owner works.

**Comment by Coinwillwin** [comment]
Hello how do I remove accounts

**Comment by BinTianqi** [comment]
> Hello how do I remove accounts

Settings -> Passwords & accounts -> *Your account(s)* -> Remove account

**Comment by Coinwillwin** [comment]
There is one account and when I try to remove it tit says "your device manufacturer has disallowed this change"

My phone is Infinix smart 7 
Android 12

**Comment by Coinwillwin** [comment]
Above the accounts there is "accounts for owner"

**Comment by Coinwillwin** [comment]
I tried to dumpsys account
It gave me a whole list but I can't copy it saved the output in the download folder

**Comment by Coinwillwin** [comment]
Then I tried it in an adb shell it said
<font color=#FF0000></font>
<font color=#FF0000>Exception occurred while executing 'set-device-owner':</font>
<font color=#FF0000>java.lang.IllegalStateException: Not allowed to set the device owner because there are already some accounts on the device.</font>
<font color=#FF0000>	at com.android.server.devicepolicy.DevicePolicyManagerService.enforceCanSetDeviceOwnerLocked(DevicePolicyManagerService.java:9492)</font>
<font color=#FF0000>	at com.android.server.devicepolicy.DevicePolicyManagerService.setDeviceOwner(DevicePolicyManagerService.java:8367)</font>
<font color=#FF0000>	at com.android.server.devicepolicy.DevicePolicyManagerServiceShellCommand.runSetDeviceOwner(DevicePolicyManagerServiceShellCommand.java:256)</font>
<font color=#FF0000>	at com.android.server.devicepolicy.DevicePolicyManagerServiceShellCommand.onCommand(DevicePolicyManagerServiceShellCommand.java:89)</font>
<font color=#FF0000>	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)</font>
<font color=#FF0000>	at android.os.ShellCommand.exec(ShellCommand.java:38)</font>
<font color=#FF0000>	at com.android.server.devicepolicy.DevicePolicyManagerService.onShellCommand(DevicePolicyManagerService.java:9831)</font>
<font color=#FF0000>	at android.os.Binder.shellCommand(Binder.java:954)</font>
<font color=#FF0000>	at android.os.Binder.onTransact(Binder.java:837)</font>
<font color=#FF0000>	at android.app.admin.IDevicePolicyManager$Stub.onTransact(IDevicePolicyManager.java:6969)</font>
<font color=#FF0000>	at android.os.Binder.execTransactInternal(Binder.java:1200)</font>
<font color=#FF0000>	at android.os.Binder.execTransact(Binder.java:1147)</font>

**Comment by BinTianqi** [comment]
Can you tell me what's the name of that account?

**Comment by BinTianqi** [comment]
@Xisrr1 Did you resolve this issue?

**Comment by Xisrr1** [comment]
> @Xisrr1 Did you resolve this issue?

Nope, only profile owner works. 

This could maybe be because I only disabled all apps with accounts (Hail app) instead of actually removing them.

**Comment by BinTianqi** [comment]
> disabled all apps with accounts

You can try to clear storage of all apps with accounts
